coding_en = [
    {"question": "What does CPU stand for?",
        "answer": "central processing unit", "wrong": ["computer process utility", "central program unit"]},
    {"question": "What symbol starts a comment in Python?",
        "answer": "#", "wrong": ["//", "$"]},
    {"question": "What does HTML stand for?",
        "answer": "hypertext markup language", "wrong": ["hotmail transfer language", "hyper tool markup logic"]},
    {"question": "What is a variable?",
        "answer": "a named storage location", "wrong": ["a fixed constant value", "a type of function"]},
    {"question": "What does 'git commit' do?",
        "answer": "saves changes to the local repository", "wrong": ["uploads code to GitHub", "deletes staged files"]},
    {"question": "What is a loop?",
        "answer": "a repeating block of code", "wrong": ["a type of variable", "a function that returns nothing"]},
    {"question": "What is an array?",
        "answer": "an ordered collection of elements", "wrong": ["a type of boolean", "a function with no parameters"]},
    {"question": "What does 'return' do in a function?",
        "answer": "sends a value back to the caller", "wrong": ["exits the program", "creates a new variable"]},
    {"question": "What is debugging?",
        "answer": "finding and fixing errors in code", "wrong": ["writing code comments", "compiling source code"]},
    {"question": "What is an algorithm?",
        "answer": "step-by-step instructions to solve a problem", "wrong": ["a type of data structure", "a programming language"]},
]

calculus_en = [
    {"question": "What is a derivative?",
        "answer": "the rate of change of a function", "wrong": ["the area under a curve", "the maximum value of a function"]},
    {"question": "What is an integral?",
        "answer": "the area under a curve", "wrong": ["the slope of a line", "the rate of change"]},
    {"question": "What is a limit?",
        "answer": "the value a function approaches", "wrong": ["the maximum of a function", "the slope at a point"]},
    {"question": "What is the derivative of x squared?",
        "answer": "two x", "wrong": ["x squared", "x cubed"]},
    {"question": "What is the chain rule used for?",
        "answer": "differentiating composite functions", "wrong": ["finding definite integrals", "solving limits"]},
    {"question": "What does a critical point indicate?",
        "answer": "where the derivative equals zero", "wrong": ["where the function is undefined", "where the limit exists"]},
    {"question": "What is an asymptote?",
        "answer": "a line the graph approaches but never touches", "wrong": ["a turning point", "a y-intercept"]},
    {"question": "What does divergence mean for a series?",
        "answer": "the series has no finite sum", "wrong": ["the series sums to zero", "the series is decreasing"]},
    {"question": "What is the fundamental theorem of calculus?",
        "answer": "it links differentiation and integration", "wrong": ["it defines the chain rule", "it proves limits exist"]},
    {"question": "What is a polynomial?",
        "answer": "an expression with variables raised to whole number powers", "wrong": ["a ratio of two functions", "a function with no variables"]},
]

fysikk_no = [
    {"question": "Hva er Newton's første lov?",
        "answer": "et legeme i ro forblir i ro", "wrong": ["kraft er masse ganger akselerasjon", "energi er alltid bevart"]},
    {"question": "Hva er enheten for kraft?",
        "answer": "newton", "wrong": ["joule", "watt"]},
    {"question": "Hva er akselerasjon?",
        "answer": "endring i hastighet over tid", "wrong": ["distanse delt på tid", "masse ganger fart"]},
    {"question": "Hva er kinetisk energi?",
        "answer": "energi fra bevegelse", "wrong": ["lagret potensiell energi", "varmeenergi"]},
    {"question": "Hva sier Ohms lov?",
        "answer": "spenning er strøm ganger motstand", "wrong": ["kraft er masse ganger akselerasjon", "effekt er arbeid delt på tid"]},
    {"question": "Hva er frekvens?",
        "answer": "antall svingninger per sekund", "wrong": ["bølgelengde delt på tid", "amplitude ganger tid"]},
    {"question": "Hva er tyngdeakselerasjonen på jorda?",
        "answer": "9.8 meter per sekund i kvadrat", "wrong": ["1 meter per sekund i kvadrat", "5 meter per sekund i kvadrat"]},
    {"question": "Hva er enheten for energi?",
        "answer": "joule", "wrong": ["newton", "watt"]},
    {"question": "Hva er refleksjon av lys?",
        "answer": "lys spretter tilbake fra en overflate", "wrong": ["lys bøyes gjennom et medium", "lys absorberes av overflaten"]},
    {"question": "Hva er potensiel energi?",
        "answer": "energi lagret på grunn av posisjon", "wrong": ["energi fra bevegelse", "energi fra varme"]},
]

popvitenskap_no = [
    {"question": "Hva er et svart hull?",
        "answer": "en region der ingenting kan rømme gravitasjonen", "wrong": ["en stjerne uten lys", "en planet uten atmosfære"]},
    {"question": "Hva er evolusjon?",
        "answer": "artens endring over generasjoner gjennom naturlig utvalg", "wrong": ["overføring av genetisk informasjon direkte", "cellenes vekst og deling"]},
    {"question": "Hva er DNA?",
        "answer": "et molekyl som bærer genetisk informasjon", "wrong": ["en type protein", "en organelle i cellen"]},
    {"question": "Hva kalles den nærmeste stjernen til jorda?",
        "answer": "solen", "wrong": ["proxima centauri", "sirius"]},
    {"question": "Hva er fotosyntese?",
        "answer": "planter lager mat fra sollys og karbondioksid", "wrong": ["dyr puster ut oksygen", "sopp bryter ned organisk materiale"]},
    {"question": "Hva er kunstig intelligens?",
        "answer": "maskiner som etterligner menneskelig tenkning", "wrong": ["programvare for avansert matematikk", "en type internettforbindelse"]},
    {"question": "Hva er universets omtrentlige alder?",
        "answer": "13.8 milliarder år", "wrong": ["4.5 milliarder år", "1 billion år"]},
    {"question": "Hva er et gen?",
        "answer": "en sekvens av DNA som koder for et protein", "wrong": ["en type celle", "en del av cellemembranen"]},
    {"question": "Hva er klimaendringer?",
        "answer": "langsiktige endringer i jordens gjennomsnittstemperatur", "wrong": ["kortvarige værforhold", "sesongmessige temperaturvariasjoner"]},
    {"question": "Hva er et atom?",
        "answer": "minste enhet av et grunnstoff", "wrong": ["en type molekyl", "en del av atomkjernen"]},
]
